/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DependantsRouteImport } from './routes/dependants'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as NewDutyRouteImport } from './routes/new-duty'
import { Route as NewLeisureRouteImport } from './routes/new-leisure'
import { Route as RequestIdRouteImport } from './routes/request.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DependantsRoute = DependantsRouteImport.update({
  id: '/dependants',
  path: '/dependants',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const NewDutyRoute = NewDutyRouteImport.update({
  id: '/new-duty',
  path: '/new-duty',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLeisureRoute = NewLeisureRouteImport.update({
  id: '/new-leisure',
  path: '/new-leisure',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dependants': typeof DependantsRoute
  '/home': typeof HomeRoute
  '/my-requests': typeof MyRequestsRoute
  '/new-duty': typeof NewDutyRoute
  '/new-leisure': typeof NewLeisureRoute
  '/request/$id': typeof RequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dependants': typeof DependantsRoute
  '/home': typeof HomeRoute
  '/my-requests': typeof MyRequestsRoute
  '/new-duty': typeof NewDutyRoute
  '/new-leisure': typeof NewLeisureRoute
  '/request/$id': typeof RequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dependants': typeof DependantsRoute
  '/home': typeof HomeRoute
  '/my-requests': typeof MyRequestsRoute
  '/new-duty': typeof NewDutyRoute
  '/new-leisure': typeof NewLeisureRoute
  '/request/$id': typeof RequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dependants'
    | '/home'
    | '/my-requests'
    | '/new-duty'
    | '/new-leisure'
    | '/request/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dependants'
    | '/home'
    | '/my-requests'
    | '/new-duty'
    | '/new-leisure'
    | '/request/$id'
  id:
    | '__root__'
    | '/'
    | '/dependants'
    | '/home'
    | '/my-requests'
    | '/new-duty'
    | '/new-leisure'
    | '/request/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DependantsRoute: typeof DependantsRoute
  HomeRoute: typeof HomeRoute
  MyRequestsRoute: typeof MyRequestsRoute
  NewDutyRoute: typeof NewDutyRoute
  NewLeisureRoute: typeof NewLeisureRoute
  RequestIdRoute: typeof RequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependants': {
      id: '/dependants'
      path: '/dependants'
      fullPath: '/dependants'
      preLoaderRoute: typeof DependantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-duty': {
      id: '/new-duty'
      path: '/new-duty'
      fullPath: '/new-duty'
      preLoaderRoute: typeof NewDutyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-leisure': {
      id: '/new-leisure'
      path: '/new-leisure'
      fullPath: '/new-leisure'
      preLoaderRoute: typeof NewLeisureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DependantsRoute: DependantsRoute,
  HomeRoute: HomeRoute,
  MyRequestsRoute: MyRequestsRoute,
  NewDutyRoute: NewDutyRoute,
  NewLeisureRoute: NewLeisureRoute,
  RequestIdRoute: RequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
